ender_pearl_cooldown_ticks: 240
new_player_protection_hours: 24
player_head_drop_chance: 0.1
arena_keepinv_requires_combat_tag: true
armor:
  # Global armor settings
  enabled: true # Enable/disable entire armor system
  dodge_enabled: true # Enable dodge mechanics
  swimming_restrictions: true # Restrict swimming in heavy armor
  hunger_penalties: true # Apply hunger penalties
  durability_penalties: true # Apply penalties for damaged armor
  crossbow_armor_piercing: 0.3 # Percentage of armor bypassed by crossbows (0.3 = 30%)
  max_protection: 0.8 # Maximum protection percentage (0.8 = 80%)
  max_dodge_chance: 0.25 # Maximum dodge chance (0.25 = 25%)

  # Light Armor Stats (Leather/Chain + custom Nexo items starting with "light_")
  light:
    protection_multiplier: 0.0 #
    speed_multiplier: 0.95 # 95% movement speed
    jump_multiplier: 1.0 # 100% jump height
    dodge_chance: 0.15 # 15% dodge chance per piece
    hunger_multiplier: 0.1 # Additional hunger drain in combat
    stamina_multiplier: 1.0 # Normal stamina

  # Medium Armor Stats (Iron + custom Nexo items starting with "medium_")
  medium:
    protection_multiplier: 0.05 #
    speed_multiplier: 0.85 #
    jump_multiplier: 0.98 #
    dodge_chance: 0.08 # 8% dodge chance per piece
    hunger_multiplier: 0.05 # Slight hunger drain in combat
    stamina_multiplier: 0.8 # 80% stamina

  # Heavy Armor Stats (Diamond/Netherite + custom Nexo items starting with "heavy_")
  heavy:
    protection_multiplier: 0.1 # 60% protection per piece
    speed_multiplier: 0.8 # 70% movement speed
    jump_multiplier: 0.95 # 70% jump height
    dodge_chance: 0.0 # No dodge chance
    hunger_multiplier: 0.0 # No additional hunger drain
    stamina_multiplier: 0.5 # 50% stamina

  # Wizard Armor Stats (Custom Nexo items starting with "wizard_")
  wizard:
    protection_multiplier: 0.05 # 5% protection per piece
    speed_multiplier: 1.0 # Normal movement speed
    jump_multiplier: 1.0 # 110% jump height
    dodge_chance: 0.2 # 20% dodge chance per piece
    hunger_multiplier: 0.15 # Increased hunger drain in combat
    stamina_multiplier: 1.1 # 120% stamina
