name: OrbisCombat
version: ${project.version}
main: net.earthmc.emccom.EMCCOM
api-version: '1.20'
authors: [ Foksha, Error110, Windows10Laptop, CorruptedGreed ]
description: A combat plugin!
depend: [Towny]

folia-supported: true

commands:
  orbiscombat:
    description: Main OrbisCombat command with subcommands for combat management.
    permission: emccom.command.basic
    permission-message: You do not have permission to run this command!
    usage: /orbiscombat help
    aliases: [oc]
  combat:
    description: Alias for OrbisCombat command.
    permission: emccom.command.basic
    permission-message: You do not have permission to run this command!
    usage: /combat help
  combattag:
    description: Legacy command for combat tagging (backwards compatibility).
    permission: emccom.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help

permissions:
  emccom.command.basic:
    description: Allows access to basic OrbisCombat commands
    default: true
  emccom.command.combattag:
    description: Allows access to combat tag management commands
    default: op
  emccom.combattag.bypass:
    description: Allows bypassing combat tag restrictions
    default: false