name: OrbisCombat
version: ${project.version}
main: net.earthmc.emccom.EMCCOM
api-version: '1.21'
authors: [ Foksha, Error110, Windows10Laptop, CorruptedGreed ]
description: A combat plugin with advanced armor system!
depend: [Towny]
softdepend: [Nexo]

folia-supported: true

commands:
  orbiscombat:
    description: Main OrbisCombat command with subcommands for combat management.
    permission: emccom.command.basic
    permission-message: You do not have permission to run this command!
    usage: /orbiscombat help
    aliases: [oc]
  combat:
    description: Alias for OrbisCombat command.
    permission: emccom.command.basic
    permission-message: You do not have permission to run this command!
    usage: /combat help
  combattag:
    description: Legacy command for combat tagging (backwards compatibility).
    permission: emccom.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help
  armor:
    description: Check armor statistics and manage armor system.
    permission: emccom.command.armor
    permission-message: You do not have permission to run this command!
    usage: /armor help
    aliases: [armorstats, armour]

permissions:
  emccom.command.basic:
    description: Allows access to basic OrbisCombat commands
    default: true
  emccom.command.combattag:
    description: Allows access to combat tag management commands
    default: op
  emccom.command.armor:
    description: Allows access to armor status commands
    default: true
  emccom.command.armor.refresh:
    description: Allows refreshing armor calculations for players
    default: op
  emccom.combattag.bypass:
    description: Allows bypassing combat tag restrictions
    default: false